- name: Add Longhorn Helm repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Update Helm repositories
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
    state: present
  when: inventory_hostname == 'rke2-master1'

- name: Copy values.yaml to target host
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/longhorn/values/values.yaml"
    dest: "/tmp/longhorn-values.yaml"
    mode: '0644'
  when: inventory_hostname == 'rke2-master1'

- name: Install/upgrade Longhorn using Helm
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: "longhorn-system"
    create_namespace: true
    state: present
    chart_version: "1.9.1"
    values_files:
      - /tmp/longhorn-values.yaml
  when: inventory_hostname == 'rke2-master1'


- name: Wait for Longhorn pods to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: longhorn-system
  register: longhorn_pods
  until: >
    longhorn_pods.resources | map(attribute='status.phase') | select('equalto', 'Running') | list | length == longhorn_pods.resources | length
  retries: 10
  delay: 60
  when: inventory_hostname == 'rke2-master1'
