- name: Install haproxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true

- name: Allow nonlocal bind
  ansible.posix.sysctl:
    name: "net.ipv4.ip_nonlocal_bind"
    value: "1"
    state: present
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/99-haproxy-vip.conf
    reload: true

- name: Deploy haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: Restart haproxy

- name: Enable haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true
